import fs from 'node:fs';
import { performance } from 'node:perf_hooks';
import { inspect } from 'node:util';
import { getUtils } from './Bootstrap';

const { createSimpleLogger } = await getUtils();

class Logger {
    protected github = new GithubActions();
    protected log;
    protected static DEBUG_ENV_TRIGGERS = [
        'true',
        '*',
        'vite-bundler:*',
    ]
    constructor() {
        const debugEnv = process.env.DEBUG || 'false';
        const debugEnabled = !!debugEnv.trim().split(/\s+/).find((field) => {
            return Logger.DEBUG_ENV_TRIGGERS.includes(field.trim())
        });
        this.log = createSimpleLogger('vite-bundler', { debug: debugEnabled });
    }
    
    public info(message: string, ...args: LogMethodArgs) {
        this.log.info(message, ...args);
    }
    public error(message: string, ...args: LogMethodArgs) {
        this.github.annotate(message, {});
        this.log.error(message, ...args);
    }
    public warn(message: string, ...args: LogMethodArgs) {
        this.log.warn(message, ...args);
    }
    public success(message: string, ...args: LogMethodArgs) {
        this.log.success(message, ...args);
    }
    public debug(message: string, ...args: LogMethodArgs) {
        this.log.debug(message, ...args)
    }
    
    public startProfiler() {
        const startTime = performance.now();
        return {
            complete: (message: string) => {
                const messageWithTiming = `${message} in ${msToHumanTime(performance.now() - startTime)}`
                this.success(messageWithTiming);
                this.github.summarize(messageWithTiming);
            }
        }
    }
}

class GithubActions {
    protected readonly summaryLines: string[] = [];
    protected stepSummaryFile;
    protected useAnnotations;
    
    constructor() {
        if (process.env.METEOR_VITE_DISABLE_CI_SUMMARY === 'true') {
            return;
        }
        this.stepSummaryFile = process.env.GITHUB_STEP_SUMMARY;
        this.useAnnotations = !!this.stepSummaryFile;
    }
    
    public annotate(message: string, options: GithubAnnotationOptions = {}) {
        if (!this.useAnnotations) {
            return;
        }
        const data: string[] = Object.entries(options).map(([key, value]) => {
            return `${key}="${value}"`
        });
        
        console.log(`::notice ${data.join()}::⚡  ${message}`);
    }
    
    public summarize(message: string, ...args: LogMethodArgs) {
        if (!this.stepSummaryFile) {
            return;
        }
        
        const formattedArgs = args.length ? inspect(args) : '';
        this.summaryLines.push(`⚡  ${message} ${formattedArgs}`);
        const summary = [
            '```log',
            'Meteor-Vite build metrics:',
            ...this.summaryLines,
            '```',
            '',
            '<details>',
            '<summary>Generated by Meteor Vite</summary>',
            '\n',
            'Step summary generated by [`jorgenvatle:vite-bundler`](https://github.com/JorgenVatle/meteor-vite)',
            'You can disable this behaviour with an environment variable: `METEOR_VITE_DISABLE_CI_SUMMARY=false`',
            '',
            '</details>',
            '',
        ]
        fs.writeFileSync(this.stepSummaryFile, summary.join('\n'));
    }
}

interface GithubAnnotationOptions {
    title?: string;
}

type LogMethodArgs = unknown[];
export default new Logger();

function msToHumanTime(milliseconds: number) {
    const duration = {
        count: milliseconds,
        type: 'ms',
    }
    
    if (milliseconds > 1000) {
        duration.count = milliseconds / 1000;
        duration.type = 's';
    }
    
    if (duration.type === 's' && duration.count > 60) {
        duration.type = 'min'
        duration.count = duration.count / 60;
    }
    
    return `${Math.round(duration.count * 100) / 100}${duration.type}`;
}
