# Base deployment manifest
# Use `$ envsubst` to populate fields in the manifest before applying it.
# Ex: `cat .kubernetes/deployments/meteor.yml | envsubst | kubectl apply -f -`
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "${APP_NAME}"
  labels:
    app.kubernetes.io/name: meteor-vite-example
    app.kubernetes.io/component: meteor
    app.kubernetes.io/instance: "${APP_NAME}"
    app.kubernetes.io/version: "${DEPLOYMENT_VERSION}"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: meteor-vite-example
      app.kubernetes.io/component: meteor
      app.kubernetes.io/instance: "${APP_NAME}"
  template:
    spec:
      containers:
        - name: meteor
          image: "${IMAGE_TAG}"
          ports:
            - containerPort: 3000
              name: meteor
          env:
            - name: PORT
              value: '3000'
            - name: ROOT_URL
              value: 'https://${APP_NAME}--meteor-vite.example.com'
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: meteor
                  key: mongoConnectionUri
            - name: MONGO_OPLOG_URL
              valueFrom:
                secretKeyRef:
                  name: meteor
                  key: mongoOplogConnectionUri
          resources:
            requests:
              cpu: 50m
              memory: 75Mi
            limits:
              cpu: 500m
              memory: 512Mi

