import type { LoggerParams } from '@/utilities/server/logger/LoggerInstance';
import fs from 'node:fs';
import { inspect } from 'node:util';

export class GithubActionsAnnotator {
    protected readonly summaryLines: string[] = [];
    protected stepSummaryFile;
    protected useAnnotations;
    
    constructor() {
        if (process.env.METEOR_VITE_DISABLE_CI_SUMMARY === 'true') {
            return;
        }
        this.stepSummaryFile = process.env.GITHUB_STEP_SUMMARY;
        this.useAnnotations = !!this.stepSummaryFile;
    }
    
    public annotate([message]: unknown[], options: GithubAnnotationOptions = {}) {
        if (!this.useAnnotations) {
            return;
        }
        const data: string[] = Object.entries(options).map(([key, value]) => {
            return `${key}="${value}"`
        });
        
        console.log(`::notice ${data.join()}::⚡  ${message}`);
    }
    
    public summarize(message: string, ...args: LoggerParams) {
        if (!this.stepSummaryFile) {
            return;
        }
        
        const formattedArgs = args.length ? inspect(args) : '';
        this.summaryLines.push(`⚡  ${message} ${formattedArgs}`);
        const summary = [
            '```log',
            'Meteor-Vite build metrics:',
            ...this.summaryLines,
            '```',
            '',
            '<details>',
            '<summary>Generated by Meteor Vite</summary>',
            '\n',
            'Step summary generated by [`jorgenvatle:vite-bundler`](https://github.com/JorgenVatle/meteor-vite)',
            'You can disable this behaviour with an environment variable: `METEOR_VITE_DISABLE_CI_SUMMARY=false`',
            '',
            '</details>',
            '',
        ]
        fs.writeFileSync(this.stepSummaryFile, summary.join('\n'));
    }
}

interface GithubAnnotationOptions {
    title?: string;
}