name: Cypress Tests

on:
  workflow_call:
    inputs:
      appBasename:
        type: string
        required: true

jobs:
  build:
    name: Build 🐋
    uses: ./.github/workflows/_reuse_.build.yml
    secrets: inherit
    with:
      appBasename: ${{ inputs.appBasename }}
      push: false

  cypress-run:
    runs-on: ubuntu-24.04
    needs: build
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
    env:
      APP_IMAGE: ${{ needs.build.outputs.deploymentImage }}
      APP_BASENAME: ${{ inputs.appBasename }}
      PORT: 3000
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: test/cypress-suite
          build: npm run pull-image ${{ env.APP_IMAGE }}
          start: npm start