name: 'Reusable: Build'
on:
  workflow_call:
    inputs:
      appBasename:
        required: true
        type: string
      meteorRelease:
        type: string
        default: '2.12'
      environment:
        type: string
        default: 'ubuntu'

jobs:
  build-on-ubuntu:
    name: 'Build on Ubuntu'
    runs-on: ubuntu-latest
    if: inputs.environment == 'ubuntu'
    timeout-minutes: 10
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Setup Meteor'
        uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: ${{ inputs.meteorRelease }}

      - name: 'Install dependencies'
        run: meteor npm run example install ${{ inputs.appBasename }}

      - name: 'Link meteor-vite package'
        run: meteor npm run example link ${{ inputs.appBasename }}

      - name: 'Build for production'
        run: meteor npm run example build ${{ inputs.appBasename }}

