name: 'Deploy Preview'
run-name: '🚀 Deploy: ${{ inputs.appBasename }}'
on:
  workflow_call:
    inputs:
      appBasename:
        type: string
        description: | 
          Basename for the directory containing the example app being deployed.
          Can only contain lowercase alphanumeric characters, `-` and `_`.
          Example: vue, react, vue-meteor-v3
        required: true
      imageRegistry:
        type: string
        default: ghcr.io
      meteorBaseImage:
        type: string
        required: false
        description: |
          Meteor base image for bundling. Useful to override if you need a Meteor release not officially
          supported yet by the original geoffreybooth image.
      nodeVersion:
        type: string
        required: false
        description: Node.js Docker image version to use for the final production build.

env:
  APP_NAMESPACE: meteor-vite
  METEOR_RELEASE: ${{ inputs.meteorRelease }}
  APP_NAME: ${{ github.ref_name }}-${{ inputs.appBasename }}
  ROOT_URL: https://meteor-vite-preview.wcaserver.com/${{ github.ref_name }}/${{ inputs.appBasename }}/
jobs:
  build:
    name: Build 🐋
    uses: ./.github/workflows/_reuse_.build.yml
    secrets: inherit
    with:
      appBasename: ${{ inputs.appBasename }}
      nodeVersion: ${{ inputs.nodeVersion }}
      meteorBaseImage: ${{ inputs.meteorBaseImage }}
      push: true

  deploy:
    name: Deploy 🚀
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ inputs.appBasename }}

    environment:
      name: ${{ github.ref_name }}-${{ inputs.appBasename }}
      url: ${{ env.ROOT_URL }}
    env:
      APP_VERSION: ${{ needs.build.outputs.imageVersion }}
      APP_IMAGE: ${{ needs.build.outputs.deploymentImage }}
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kubectl
        # language="bash"
        run: |
          mkdir -p ~/.kube
          echo '${{ secrets.KUBE_CONFIG_DATA }}' | base64 -d > ~/.kube/config

      - name: Apply manifest
        # language="bash"
        run: |
          MANIFEST_STORE_PATH='/opt/manifests/deployments'
          DEPLOYMENT_FILE_PATH="$MANIFEST_STORE_PATH/meteor.yml"
          
          # Populate environment variables in deployment manifest
          mkdir -p "$MANIFEST_STORE_PATH"
          cat .kubernetes/deployments/meteor.yml | envsubst > $DEPLOYMENT_FILE_PATH
          
          # Emit copy of final manifest to step summary
          echo '
          <details>
          <summary>Deployment manifest</summary>
          
          ```yaml
          ' >> $GITHUB_STEP_SUMMARY
          cat $DEPLOYMENT_FILE_PATH >> $GITHUB_STEP_SUMMARY
          echo '
          ```
          </details>
          ' >> $GITHUB_STEP_SUMMARY
          
          # Deploy
          kubectl apply -f "$DEPLOYMENT_FILE_PATH" -n "$APP_NAMESPACE"

      - name: Verify deployment
        # language="bash"
        run: |
          kubectl rollout status deployment --watch --timeout 60s -n "$APP_NAMESPACE" "$APP_NAME"

      - name: Update preview ingress
        # language="bash"
        run: |
          node .bin/patch-ingress.mjs