name: 'Reusable: Build'
on:
  workflow_call:
    inputs:
      appBasename:
        required: true
        type: string
      meteorRelease:
        type: string
        required: false
      nodeVersion:
        type: string
        required: false
      push:
        type: boolean
        default: false
      imageRegistry:
        type: string
        default: ghcr.io
      meteorBaseImage:
        type: string
        required: false
      target:
        type: string
        default: "universal"
      viteBaseUrl:
        type: string
        required: false
        description: Base path or URL that will be used for serving Vite assets. Primarily for serving assets through an external CDN.
      viteAssetDir:
        type: string
        required: false
        description: Sets the path from where Meteor will serve assets built by Vite.
    outputs:
      deploymentImage:
        value: ${{ jobs.docker.outputs.deploymentImage }}
      imageVersion:
        value: ${{ jobs.docker.outputs.imageVersion }}
      meteorRelease:
        value: ${{ jobs.docker.outputs.meteorRelease }}
      viteAssetDir:
        value: ${{ jobs.docker.outputs.viteAssetDir }}

jobs:
  ubuntu:
    name: 'Ubuntu 🐧'
    runs-on: ubuntu-latest
    if: inputs.push != true && inputs.target != 'docker'
    timeout-minutes: 10
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Setup Meteor'
        uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: ${{ inputs.meteorRelease }}

      - name: 'Install dependencies'
        run: meteor npm i

      - name: 'Build packages'
        run: meteor npm run build:packages

      - name: 'Build for production'
        run: meteor npm run build ${{ inputs.appBasename }}

  docker:
    runs-on: ubuntu-latest
    name: Docker 🐋
    env:
      APP_BASENAME: ${{ inputs.appBasename }}
    outputs:
      deploymentImage: ${{ steps.image.outputs.deploymentImage }}
      imageVersion: ${{ steps.image.outputs.imageVersion }}
      meteorRelease: ${{ steps.image.outputs.meteorRelease }}
      viteAssetDir: ${{ steps.image.outputs.viteAssetDir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Format image name
        id: image
        env:
          METEOR_VITE_BASE_URL: /${{ github.ref_name }}/${{ inputs.appBasename }}
        # language="bashsupport pro shell script"
        run: |
          meteorRelease="$(cat 'examples/${{ inputs.appBasename }}/.meteor/release' | cut -d '@' -f 2)"
          imageName="${{ inputs.imageRegistry }}/${{ github.repository_owner }}/meteor-vite/example/${{ github.ref_name }}/${{ inputs.appBasename }}"
          imageName="$(echo $imageName | tr '[:upper:]' '[:lower:]')"
          imageVersion="sha-${GITHUB_SHA:0:7}"
          viteBaseUrl=${{ inputs.viteBaseUrl || env.METEOR_VITE_BASE_URL }}
          viteAssetDir=${{ inputs.viteAssetDir }}

          echo "cacheTag=$imageName:buildcache" >> $GITHUB_OUTPUT
          echo "deploymentImage=$imageName:$imageVersion" >> $GITHUB_OUTPUT

          echo "imageName=$imageName" >> $GITHUB_OUTPUT
          echo "imageVersion=$imageVersion" >> $GITHUB_OUTPUT
          echo "meteorRelease=$meteorRelease" >> $GITHUB_OUTPUT
          echo "viteAssetDir=$viteAssetDir" >> $GITHUB_OUTPUT
          echo "viteBaseUrl=$viteBaseUrl" >> $GITHUB_OUTPUT

      - name: Prepare metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{ steps.image.outputs.imageName }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ${{ inputs.push && 'Build & Push' || 'Build' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ inputs.push }}
          tags: |
            ${{ steps.image.outputs.deploymentImage }}
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ steps.image.outputs.cacheTag }}
          cache-to: type=registry,ref=${{ steps.image.outputs.cacheTag }},mode=max
          build-args: |
            ${{ inputs.meteorBaseImage   && format('METEOR_BASE_IMAGE={0}', inputs.meteorBaseImage)        }}
            ${{ inputs.nodeVersion       && format('NODE_VERSION={0}', inputs.nodeVersion)                 }}
            METEOR_VITE_BASE_URL${{ steps.image.outputs.viteBaseUrl }}
            METEOR_VITE_ASSETS_DIR=${{ steps.image.outputs.viteAssetDir }}
            METEOR_RELEASE=${{ steps.image.outputs.meteorRelease }}
            APP_BASENAME=${{ inputs.appBasename }}
            
