name: Cypress Tests

on:
  workflow_call:
    inputs:
      appBasename:
        type: string
        required: true
      port:
        type: string
        default: 3000
      mongoPort:
        type: string
        default: 27017

jobs:
  build:
    name: Build 🐋
    uses: ./.github/workflows/_reuse_.build.yml
    secrets: inherit
    with:
      appBasename: ${{ inputs.appBasename }}
      target: 'docker'
      push: true

  cypress-run:
    runs-on: ubuntu-24.04
    needs: build
    env:
      APP_IMAGE: ${{ needs.build.outputs.deploymentImage }}
      APP_BASENAME: ${{ inputs.appBasename }}
      MONGO_URL: mongodb://mongo:${{ inputs.mongoPort }}
      PORT: ${{ inputs.port }}
      ROOT_URL: http://localhost:${{ inputs.port }}/${{ github.ref_name }}/${{ inputs.appBasename }}
      MONGO_PORT: ${{ inputs.mongoPort }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: tests/cypress-suite/cypress/screenshots
          if-no-files-found: error
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run setup ${{ env.APP_IMAGE }}
          start: npm run start
          wait-on: ${{ env.ROOT_URL }}
          working-directory: tests/cypress-suite
          spec: cypress/e2e/examples/${{ inputs.appBasename }}/**