name: 'Deploy Preview'
run-name: '🚀 Deploy: ${{ inputs.displayName }}'
on:
  workflow_call:
    inputs:
      displayName:
        type: string
        description: Name of the app being deployed
        required: true
      appDir:
        type: string
        description: Basename for the directory containing the example app being deployed.
        required: true
      imageName:
        type: string
        default: '${{ env.github.repository.owner }}/meteor-vite.example.${{ inputs.appDir }}'
      imageRegistry:
        type: string
        default: ghcr.io
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    env:
      DOCKER_CACHE_TAG: ${{ inputs.imageRegistry }}/${{ inputs.imageName }}:buildcache
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ghcr.io/JorgenVatle/meteor-vite.example.${{ inputs.appDir }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.DOCKER_CACHE_TAG }}
          cache-to: type=registry,ref=${{ env.DOCKER_CACHE_TAG }},mode=max
          build-args: |
            APP_DIR=./examples/${{ inputs.appDir }}

