name: 'Deploy Preview'
run-name: '🚀 Deploy: ${{ inputs.appBasename }}'
on:
  workflow_call:
    inputs:
      appBasename:
        type: string
        description: |
          Basename for the directory containing the example app being deployed.
          Can only contain lowercase alphanumeric characters, `-` and `_`.
          Example: vue, react, vue-meteor-v3
        required: true
      imageRegistry:
        type: string
        default: ghcr.io
      meteorBaseImage:
        type: string
        required: false
        description: |
          Meteor base image for bundling. Useful to override if you need a Meteor release not officially
          supported yet by the original geoffreybooth image.
      nodeVersion:
        type: string
        required: false
        description: Node.js Docker image version to use for the final production build.
      viteBaseUrl:
        type: string
        required: false
      viteAssetDir:
        type: string
        required: false
      eventName:
        type: string
        required: false
        description: Name of the event that triggered this workflow

jobs:
  build:
    name: Build 🐋
    uses: ./.github/workflows/_reuse_.build.yml
    secrets: inherit
    with:
      appBasename: ${{ inputs.appBasename }}
      nodeVersion: ${{ inputs.nodeVersion }}
      meteorBaseImage: ${{ inputs.meteorBaseImage }}
      viteBaseUrl: ${{ inputs.viteBaseUrl }}
      viteAssetDir: ${{ inputs.viteAssetDir }}
      push: true

  deploy:
    name: Deploy 🚀
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ inputs.appBasename }}
    environment:
      name: ${{ inputs.appBasename }}/${{ github.ref_name }}
      url: ${{ env.ROOT_URL }}
    env:
      KUBE_APP_NAME: ${{ inputs.appBasename }}
      KUBE_APP_VERSION: ${{ needs.build.outputs.imageVersion }}
      KUBE_REMOVE_AFTER: ${{ (inputs.eventName == 'pull_request' && '1m') || ''  }}
      KUBE_INGRESS_BASE_PATH: ${{ needs.build.outputs.basePath }}
      KUBE_INGRESS_NAME: preview
      KUBE_DEPLOYMENT_TIMEOUT: 30s
      KUBE_NAMESPACE: meteor-vite
      KUBE_CONTAINER_PORT: 3000
      KUBE_CONTAINER_IMAGE: ${{ needs.build.outputs.deploymentImage }}
      METEOR_VERSION: ${{ needs.build.outputs.meteorRelease }}
      ROOT_URL: https://meteor-vite-preview.wcaserver.com${{ needs.build.outputs.basePath }}
      METEOR_RELEASE: ${{ needs.build.outputs.meteorRelease }}
      PULL_REQUEST_ID: ${{ github.event.pull_request.id }}
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup kubectl
        # language="bash"
        run: |
          mkdir -p ~/.kube
          echo '${{ secrets.KUBE_CONFIG_DATA }}' | base64 -d > ~/.kube/config

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build:packages

      - name: Apply manifest
        # language="bash"
        run: npm exec toolkit kube-deploy -- -f .kubernetes/deployments/meteor.yml

      - name: Verify successful deployment
        # language="bash"
        run: npm exec toolkit kube-verify-deployment

      - name: Update preview ingress
        # language="bash"
        run: npm exec toolkit kube-sync-ingress