name: 'Deploy Preview'
run-name: '🚀 Deploy: ${{ inputs.displayName }}'
on:
  workflow_call:
    inputs:
      displayName:
        type: string
        description: Name of the app being deployed
        required: true
      appDir:
        type: string
        description: Basename for the directory containing the example app being deployed.
        required: true
      imageRegistry:
        type: string
        default: ghcr.io
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Format image name
        id: image
        # language="bashpro shell script"
        run: |
          imageName="${{ github.repository_owner }}/meteor-vite.example.${{ inputs.appDir }}"
          echo "imageName=$imageName" >> $GITHUB_OUTPUT
          echo "cacheTag=$imageName:buildcache" >> $GITHUB_OUTPUT

      - name: Prepare metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{ steps.image.outputs.imageName }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ steps.image.outputs.cacheTag }}
          cache-to: type=registry,ref=${{ steps.image.outputs.cacheTag }},mode=max
          build-args: |
            APP_DIR=./examples/${{ inputs.appDir }}

