name: 'Build'
run-name: 'Build: ${{ github.event.head_commit.message || github.event.pull_request.title }}'

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release

jobs:
  vue:
    name: 'Vue'
    uses: ./.github/workflows/_reuse_.build.yml
    with:
      name: 'vue'

  svelte:
    name: 'Svelte'
    uses: ./.github/workflows/_reuse_.build.yml
    with:
      name: 'svelte'

  react:
    name: 'React'
    uses: ./.github/workflows/_reuse_.build.yml
    with:
      name: 'react'

  solid:
    name: 'Solid'
    uses: ./.github/workflows/_reuse_.build.yml
    with:
      name: 'solid'