name: 'Deploy: Example Apps'
run-name: '🚀 Deploy: Example Apps | ${{ github.event.head_commit.message || github.event.pull_request.title }}'

on:
  push:
    branches:
      - main
      - release

jobs:
  vue:
    name: '${{ matrix.name }}'
    uses: ./.github/workflows/_reuse_.deploy.yml
    secrets: inherit
    with:
      appBasename: '${{ matrix.basename }}'
      nodeVersion: ${{ matrix.nodeVersion }}
      meteorBaseImage: ${{ matrix.meteorBaseImage }}
    strategy:
      matrix:
        include:
          - name: Vue
            basename: vue

          - name: Svelte
            basename: svelte

          - name: React
            basename: react

          - name: Solid.js
            basename: solid

          - name: Meteor V3 + Vue
            basename: meteor-v3-vue
            meteorBaseImage: jorgenvatle/meteor-base
            nodeVersion: 20-alpine
