name: 'Deploy Example Apps'
run-name: '🚀 Deploy Example Apps: ${{ github.event.head_commit.message || github.event.pull_request.title }}'

on:
  push:
    branches:
      - main
      - release
      - beta
  pull_request:
    branches:
      - release

env:
  REMOVE_AFTER: ${{ (github.event_name == 'pull_request' && '1m') }}
  BRANCH_ID: ${{ (github.event_name == 'pull_request' && 'tmp-preview') || github.ref_name }}


jobs:
  vue:
    name: 'Vue'
    uses: ./.github/workflows/_reuse_.deploy.yml
    secrets: inherit
    with:
      appBasename: 'vue'
      removeAfter: ${{ env.REMOVE_AFTER }}
      branchId: '${{ env.BRANCH_ID }}'

  svelte:
    name: 'Svelte'
    uses: ./.github/workflows/_reuse_.deploy.yml
    secrets: inherit
    with:
      appBasename: 'svelte'
      removeAfter: ${{ env.REMOVE_AFTER }}
      branchId: '${{ env.BRANCH_ID }}'

  react:
    name: 'React'
    uses: ./.github/workflows/_reuse_.deploy.yml
    secrets: inherit
    with:
      appBasename: 'react'
      removeAfter: ${{ env.REMOVE_AFTER }}
      branchId: '${{ env.BRANCH_ID }}'

  solid:
    name: 'Solid'
    uses: ./.github/workflows/_reuse_.deploy.yml
    secrets: inherit
    with:
      appBasename: 'solid'
      removeAfter: ${{ env.REMOVE_AFTER }}
      branchId: '${{ env.BRANCH_ID }}'

  vue-zodern-relay:
    name: 'Vue + zodern:relay'
    uses: ./.github/workflows/_reuse_.deploy.yml
    secrets: inherit
    with:
      appBasename: 'vue-zodern-relay'
      removeAfter: ${{ env.REMOVE_AFTER }}
      branchId: '${{ env.BRANCH_ID }}'

  vue-ssr:
    name: 'Vue + SSR'
    uses: ./.github/workflows/_reuse_.deploy.yml
    secrets: inherit
    with:
      appBasename: 'vue-ssr'
      removeAfter: ${{ env.REMOVE_AFTER }}
      branchId: '${{ env.BRANCH_ID }}'