name: 'Test build'
run-name: '🗃️ Test build: ${{ github.event.head_commit.message || github.event.pull_request.title }}'

on:
  push:
    branches:
      - main
      - release
      - github-step-summary
  pull_request:
    branches:
      - main
      - release

jobs:
  build:
    name: '${{ matrix.name }}'
    uses: ./.github/workflows/_reuse_.build.yml
    with:
      appBasename: '${{ matrix.basename }}'
    strategy:
      matrix:
        include:
          - name: Vue
            basename: vue

          - name: Svelte
            basename: svelte

          - name: React
            basename: react

          - name: Solid.js
            basename: solid

          - name: Meteor V3 + Vue
            basename: meteor-v3-vue